In [1]:
import numpy as np

In [10]:
digits = np.array([
   ...:     [1, 2, 3],
   ...:     [4, 5, 6],
   ...:     [6, 7, 9],
   ...: ])

In [11]:
np.shape(digits)

(3, 3)

In [15]:
a = np.array([1,2,3])

In [16]:
a.shape

(3,)

In [20]:
a.size

3

In [19]:
a.ndim

1

In [17]:
a.itemsize

4

In [18]:
a.dtype

dtype('int32')

In [21]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [22]:
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [27]:
b[1,2]

4.0

In [29]:
b[0,-1]

7.0

In [30]:
b[-1,-1]

4.0

In [23]:
b.ndim

2

In [24]:
b.dtype

dtype('float64')

In [4]:
digits

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 9]])

In [2]:
import numpy as np
CURVE_CENTER = 80
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER - average
    new_grades = grades + change
    return np.clip(new_grades, grades, 100)

curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [9]:
array = ([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [4]:
average = grades.mean()
print(average)

60.75


In [5]:
table = np.array([
   ...:     [5, 3, 7, 1],
   ...:     [2, 6, 7 ,9],
   ...:     [1, 1, 1, 1],
   ...:     [4, 3, 2, 0],
   ...: ])

In [6]:
table.max()

9

In [7]:
table.max(axis=0)

array([5, 6, 7, 9])

In [8]:
table.max(axis=1)

array([7, 9, 1, 4])

In [1]:
import numpy as np
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)
numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [2]:
mask = numbers % 4 == 0
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [3]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [4]:
by_four = numbers[numbers % 4 == 0]
by_four

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [5]:
from math import e, factorial

import numpy as np

fac = np.vectorize(factorial)

def e_x(x, terms=10):
    """Approximates e^x using a given number of terms of
    the Maclaurin series
    """
    n = np.arange(terms)
    return np.sum((x ** n) / fac(n))

if __name__ == "__main__":
    print("Actual:", e ** 3)  # Using e from the standard library

    print("N (terms)\tMaclaurin\tError")

    for n in range(1, 14):
        maclaurin = e_x(3, terms=n)
        print(f"{n}\t\t{maclaurin:.03f}\t\t{e**3 - maclaurin:.03f}")

Actual: 20.085536923187664
N (terms)	Maclaurin	Error
1		1.000		19.086
2		4.000		16.086
3		8.500		11.586
4		13.000		7.086
5		16.375		3.711
6		18.400		1.686
7		19.412		0.673
8		19.846		0.239
9		20.009		0.076
10		20.063		0.022
11		20.080		0.006
12		20.084		0.001
13		20.085		0.000


In [33]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
c.shape

(2, 2, 2)

In [35]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
np.ones((1,2,2))

array([[[1., 1.],
        [1., 1.]]])

In [39]:
np.random.random_sample(a)

array([[[0.89448144, 0.02274408, 0.30671965],
        [0.6018151 , 0.42337544, 0.75874573]]])

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
arrays = np.array([-1,0,1,2])

In [48]:
np.sin(arrays)

array([-0.84147098,  0.        ,  0.84147098,  0.90929743])