In [1]:
import numpy as np

In [ ]:
numeros = [2,5,7,9]
a = np.array(numeros)
a[1] = 6
a

In [14]:
numeros = [2,5,7,9, 'Hello'] # Numpy solo maneja un unico tipo de dato dtype (dinamic type)
a = np.array(numeros) # al mezclarlos los convierte a todos al mismo
a[1] = 6
print(type(a))
print(type(a[0]))
a

<class 'numpy.ndarray'>
<class 'numpy.str_'>


array(['2', '6', '7', '9', 'Hello'], dtype='<U11')

In [15]:
numeros = [2,5,7,9, 1.5] # Numpy solo maneja un unico tipo de dato dtype (dinamic type)
a = np.array(numeros) # al mezclarlos los convierte a todos al mismo => todos float
a[1] = 6
print(type(a))
print(type(a[0]))
a

<class 'numpy.ndarray'>
<class 'numpy.float64'>


array([2. , 6. , 7. , 9. , 1.5])

In [16]:
a

array([2. , 6. , 7. , 9. , 1.5])

In [17]:
azar_enteros = np.random.randint(7,size=(4,4))
print(azar_enteros)

[[5 3 3 0]
 [2 2 4 0]
 [3 2 4 2]
 [0 5 5 6]]


In [18]:
# mascara
mascara = (azar_enteros % 2 ==0) & (azar_enteros > 2)
print(mascara)
print(azar_enteros[mascara])

[[False False False False]
 [False False  True False]
 [False False  True False]
 [False False False  True]]
[4 4 6]


In [13]:
# se pueden hacer en listas y arreglos

numeros = [3,4,8,9]
numeros_array = np.array(numeros)
print(numeros)
print(numeros_array)
#slice
print(numeros[1:])
print(numeros_array[1:])
print(len(numeros))
print(len(numeros_array))

[3, 4, 8, 9]
[3 4 8 9]
[4, 8, 9]
[4 8 9]
4
4


In [22]:
numeros_lista = list(range(8))
print(numeros_lista)
np_numeros_listas = np.arange(8)
print(np_numeros_listas)

[0, 1, 2, 3, 4, 5, 6, 7]
[0 1 2 3 4 5 6 7]


In [23]:
pares = [num for num in numeros_lista if num % 2 ==0]
pares

[0, 2, 4, 6]

In [24]:
np.sum(np_numeros_listas)

28

In [26]:
sum(numeros_lista)

28

cosas que podemos hacer con una lista pero no con Numpy

In [5]:
lista_variada = [9,2,6,9.7, "Hola Mundo!"] # una lista con elementos de varios tipos de datos diferentes
print(lista_variada)

[9, 2, 6, 9.7, 'Hola Mundo!']


In [6]:
lista_variada.append(8)
print(lista_variada)

[9, 2, 6, 9.7, 'Hola Mundo!', 8]
