In [4]:
def obtenerSoloLosMejores(estudiantes, nota1, nota2):
  '''"estudiantes" es un array de objetos "estudiante". Crea un nuevo array con el nombre y apellido de los estudiantes
    que en sus propiedades "check1" y "check2", tengan una nota mayor o igual a "nota1" y "nota2" respectivamente.
    // Ej:
    /* var estudiantes = [
          { nombre: "Mengano", apellido: "Solis", check1: 16, check2: 8},
          { nombre: "Fulano", apellido: "Rodriguez", check1: 20, check2: 20},
          { nombre: "Zutano", apellido: "Alvarez", check1: 10, check2: 0},
          { nombre: "Perengano", apellido: "Leiria", check1: 17, check2: 19}
      ] */
    // obtenerSoloLosMejores(estudiantes, 15, 15); retorna => ["Fulanito Rodriguez", "Perengano Leiria"];
  '''
  # Tu código:
  res = []
  for estudiante in estudiantes:
      if estudiante['check1'] >= nota1 and estudiante['check2'] >= nota2:
        res.append(f"{estudiante['nombre']} {estudiante['apellido']}")
  return res

In [5]:
estudiantes = [
          { 'nombre': "Mengano", 'apellido': "Solis", 'check1': 16, 'check2': 8},
          { 'nombre': "Fulano", 'apellido': "Rodriguez", 'check1': 20, 'check2': 20},
          { 'nombre': "Zutano", 'apellido': "Alvarez", 'check1': 10, 'check2': 0},
          { 'nombre': "Perengano", 'apellido': "Leiria", 'check1': 17, 'check2': 19}
      ]

In [6]:
obtenerSoloLosMejores(estudiantes, 15, 15)

['Fulano Rodriguez', 'Perengano Leiria']

In [7]:
obtenerSoloLosMejores(estudiantes, 10, 8)

['Mengano Solis', 'Fulano Rodriguez', 'Perengano Leiria']

In [10]:
def repetirCaracteres(string):
  '''Escribi una funcion llamada 'repeatCharacters' en el prototypo del objeto global String
  que reciba como parametro un string
  y devuelve un string en donde cada letra se repita una vez.
  Por ej:
  'hola'.repeatCharacters() devuelve "hhoollaa" '''

# Tu código aca:
  inicio = list(string)
  salida = []
  for letter in string:
    salida.append(letter*2)
  return "".join(salida)

In [8]:
string1 = 'hola'

In [12]:
string2 = 'hello'
repetirCaracteres(string2)

'hheelllloo'

In [11]:
repetirCaracteres(string1)

'hhoollaa'

In [30]:
def bienvenidoSr(persona):
  '''La funcion recibe un objeto "persona".
  de la forma:
  {nombre: 'Lionel
  apellido: 'Messi',
  invitado: true
  }
  Si tiene la propiedad "invitado" y, además, tiene las propiedades "nombre" y "apellido", tomar esos valores y retorna:
   "Lionel Messi, un gusto tenerlo nuevamente! Bienvenido".
  Si tiene la propiedad "invitado" y solo tiene la propiedad "apellido", retornar:
   "Bienvenido Sr. Messi".
  Si tiene la propiedad "invitado" y solo tiene la propiedad "nombre", retornar:
  "Hola Lionel, tu mesa está lista".
  En caso de que no tenga la propiedad "invitado" retornar:
  "Disculpe señor, no está invitado a la fiesta".'''
  #Tu código:
  keys = list(persona.keys())
  if persona['invitado'] == False:
    print("Disculpe señor, no está invitado a la fiesta") 
  else:
    if 'nombre' not in keys:
      print(f"Bienvenido Sr. {persona['apellido']}")
    else:
      if 'apellido' not in keys:
        print(f"Hola {persona['nombre']}, tu mesa está lista")
      else:
        print(f"{persona['nombre']} {persona['apellido']}, un gusto tenerlo nuevamente! Bienvenido")


In [28]:
messi = {'nombre': 'Lionel',
        'apellido': 'Messi',
        'invitado': True}

In [32]:
messi1 = {'nombre': 'Lionel',
        'invitado': True}
messi2 = {'apellido': 'Messi',
        'invitado': True}
messi3 = {'nombre': 'Lionel',
        'apellido': 'Messi',
        'invitado': False}

In [33]:
bienvenidoSr(messi)
bienvenidoSr(messi1)
bienvenidoSr(messi2)
bienvenidoSr(messi3)

Lionel Messi, un gusto tenerlo nuevamente! Bienvenido
Hola Lionel, tu mesa está lista
Bienvenido Sr. Messi
Disculpe señor, no está invitado a la fiesta


In [50]:
def masFrecuente(array): 
  '''La funcion llamada 'masFrecuente' recibe como argumento un array de numeros enteros
  y debe devolver el número entero que mas veces aparece (el más frecuente).
  ej:
  masFrecuente([1,1,2,3,4]) => 1
  masFrecuente([3,2,3,2,3,3]) => 3
  Nota: Los numeros pueden NO estar ordenados '''
  
  # Tu código aca:
  mas_repe = 0
  cantidad = 0
  array.sort(reverse=False)
  for x in array:
    if array.count(x) > cantidad:
      mas_repe = x
      cantidad = array.count(x)
  print(mas_repe)
  

In [51]:
masFrecuente([1,1,2,3,4])

1


In [52]:
masFrecuente([3,2,3,2,3,3])

3


In [53]:
def puntosDelEquipo(array):
  '''la funcion recibe un array con los resultados de los partidos del campeonato de futbol de un equipo
  en este formato ["3:1", "2:2", "0:1", ...]
  la funcion debe calcular y retornar cuantos puntos consiguio el equipo teniendo en cuenta:
  que su resultado es el primero en cada string
  un partido ganado suma 3 puntos, empate suma 1 punto, y perder 0!'''
  #Tu código aca:
  score = 0
  for puntaje in array:
    scoreR = list(puntaje)
    first = scoreR[0]
    last = scoreR[2]
    if first > last:
      score = score +3
    elif first == last:
      score = score + 1
  return score  

In [54]:
resultados = ['3:1', '2:2', '0:1', '1:0', '2:1', '1:2', '1:1']

In [55]:
puntosDelEquipo(resultados)

11

In [79]:
def intercambio(objeto):
  '''Devolver un objeto con los pares clave-valor intercambiados.
  Ej: intercambio({ nombre: "Fulano", apellido: "Rodriguez" }); devuelve => { Fulano: "nombre", Rodriguez: "apellido" }
  NOTA: No utilizar métodos de Object (values, keys, entries);
  '''
  # Tu código:
  newObj = {}
  for prop in objeto:
    newObj[objeto[prop]] = prop
  return newObj

In [80]:
objeto = { 'nombre': "Fulano", 'apellido': "Rodriguez" }

In [81]:
intercambio(objeto)

{'Fulano': 'nombre', 'Rodriguez': 'apellido'}

In [83]:
def calculandoAreas(figura):
    '''Constuye una funcion que reciba un objeto llamado "figura" como parametro. EL objeto, "figura" tendra las 
    propiedades "tipo", "base" y "altura".
    La funcion debe calcular el area de la figura geometrica segun tipo y retornar el resultado. 
    las figuras geometricas soportadas son:
    * Triangulo area : (base*altura)/2
    * Rectangulo area : (base*altura)
    Si el tipo de figura no es soportado, la funcion debe retornar null.
    Ejemplo:
    var figura = {tipo: triangulo, base : 6, altura: 4}
    calculandoAreas(figura) --> retorna 12
    Descripcion de la funcion:
    La funcion calculandoAreas debe retornar un numero entero.
    La funcion calculandoAreas recibe como parametros:
        * figura : un objeto con las propiedades tipo cadena de letras base (numero), altura (numero)  
    '''
    #Tu codigo aca:
    area = 0
    if figura['tipo'] == "triangulo":
        area = (figura['base']*figura['altura'])*1/2
    elif figura['tipo'] == "rectangulo":
        area = (figura['base']*figura['altura'])
    return area
        

In [84]:
figura = {'tipo': 'triangulo', 'base' : 6, 'altura': 4}

In [85]:
calculandoAreas(figura)

12.0

In [2]:
student_marks = {'Krishna': [67, 68, 69],
                'Arjun': [70, 98, 63],
                'Malika': [52 ,56 ,60]}


In [6]:
query_name = 'Malika'

In [24]:
def studentsMarkAverage(query_name):
    average_score = 0
    for i in range(3):
        average_score = average_score + float(student_marks[query_name][i])
        result = "{:.2f}".format(average_score/3)
    return result

In [25]:
studentsMarkAverage(query_name)

'56.00'

In [29]:
def studentsMarkAveragE(query_name):
    average_score = 0
    for i in range(3):
        average_score = average_score + float(student_marks[query_name][i])
        result = round(average_score/3,3)
    return result

In [31]:
studentsMarkAveragE('Arjun')

77.0

In [33]:
studentsMarkAveragE('Krishna')

68.0

In [35]:
import cmath as cm

In [36]:
cm.phase(complex(1,2))

1.1071487177940904

In [37]:
abs(complex(1,2))

2.23606797749979

In [41]:
z = complex(1,2)
print(z)

(1+2j)


In [42]:
import math

In [46]:
bc = 10
ab = 10
ac = (bc**2+ab**2)**(1/2)
m = ac/2
mc = m
print(round(math.degrees(math.asin(mc/bc))),chr(176))

45 °


In [47]:
divmod(177,10)

(17, 7)

In [51]:
a = 177
b = 10
print(a//b)
print(a%b)
print(divmod(a,b))

17
7
(17, 7)


In [54]:
import math
a = 3
b = 4
m = 5
print(pow(a,b))
print(pow(a,b,m))

81
1


In [58]:
pow(4, 3, 5)

4

In [59]:
64%5

4

In [60]:
def mi_decorador(funcion):
    def nueva_funcion(a, b):
        print("Se va a llamar")
        c = funcion(a, b)
        print("Se ha llamado")
        return c
    return nueva_funcion

@mi_decorador
def suma(a, b):
    print("Entra en funcion suma")
    return a + b

In [61]:
suma(3,5)

Se va a llamar
Entra en funcion suma
Se ha llamado


8

In [62]:
@mi_decorador
def resta(a ,b):
    print("Entra en funcion resta")
    return a - b


In [63]:
resta(5, 3)

Se va a llamar
Entra en funcion resta
Se ha llamado


2

In [ ]:
N = 12
"insert 0 5"
"insert 1 10"
"insert 0 6"
"print"
"remove 6"
"append 9"
"append 1"
"sort"
"print"
"pop"
"reverse"
"print"

In [ ]:
if __name__ == '__main__':
    N = int(input())
commands = [input() for i in range(N)]
output = []
for i in commands:
    if "insert" in i:
        position, value = int(i.split()[1]), int(i.split()[2])
        output.insert(position, value)
    if "print" in i:
        print(output)
    if "remove" in i:
        e = int(i.split()[1])
        output.remove(e)
    if "append" in i:
        e = int(i.split()[1])
        output.append(e)
    if "sort" in i:
        output.sort()
    if "pop" in i:
        output.pop()
    if "reverse" in i:
        output.reverse()

In [4]:
hash((1,2))

-3550055125485641917

In [6]:
listA = [1,2,3]
tuples = tuple(listA)
print(tuples)

(1, 2, 3)


In [19]:
N = int(input())

a = list(map(int, input().strip().split()))[:N]
tupla = tuple(a)

print(hash(tupla))

(1, 2)
-3550055125485641917


In [102]:
lst1 = [int(item) for item in input("Enter \
                the list items : ").split()]
print(lst1)

[1, 3, 4, 5]


In [24]:
hash((1, 2))

-3550055125485641917

In [66]:
import numpy as np

def arrays(arr):
    # complete this function
    # use numpy.array
    reversed_arr = np.array(arr[::-1], float)
    return reversed_arr

In [67]:
arr = [1,2,3,4,-8,-10]

In [68]:
arrays(arr)

array([-10.,  -8.,   4.,   3.,   2.,   1.])

In [72]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a.reshape((3,3))
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
# input data in same line space separated.
# first two inputs are matrix dimension n x m
# then each line contains the rows input elements in same line space separated
n, m = (input().split(" "))  
n = int(n)
m = int(m)
matrix=[]
for i in range(n):
    matrix.append(list(map(int, input().rstrip().split())))
matrix = np.array(matrix)
b = matrix.transpose()
print(b)
print(matrix.flatten())

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3 4]


In [95]:
import numpy as np
n, m, p = (input().split(" "))  
n = int(n)
m = int(m)
p = int(p)
array_1 = []
array_2 = []
for i in range(n):
    array_1.append(list(map(int, input().rstrip().split())))
array_1 = np.array(array_1)
for i in range(m):
    array_2.append(list(map(int, input().rstrip().split())))
array_2 = np.array(array_2)
b = np.concatenate((array_1,array_2),axis=0)
print(b)

[[1 2]
 [1 2]
 [1 2]
 [1 2]]


In [94]:
array_1 = np.array([[1,2],
                    [1,2],
                    [1,2],
                    [1,2]])
array_2 = np.array([[3,4],
                    [3,4],
                    [3,4]])
b = np.concatenate((array_1,array_2),axis=0)
print(b)

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [98]:
print(np.eye(8, 7, k = -1)) 

[[0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [100]:
import numpy as np
np.set_printoptions(legacy='1.13')

In [101]:
n, m = (input().split(" "))  
n = int(n)
m = int(m)
print(np.eye(n,m,k=1))

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


In [ ]:
import numpy

n, m = list(map(int, input().split()))

a = numpy.array([list(map(int, input().split())) for x in range(n)], int, )
b = numpy.array([list(map(int, input().split())) for x in range(n)], int)

print(numpy.add(a, b))
print(numpy.subtract(a, b))
print(numpy.multiply(a, b))
print(numpy.floor_divide(a, b))
print(numpy.mod(a, b))
print(numpy.power(a, b))

In [104]:
import numpy
numpy.set_printoptions(legacy='1.13')
lst1 = [float(item) for item in input().split()]
lst1 = numpy.array(lst1,dtype=float)
print(lst1)

[ 1.2  2.3  3.5  4.6  5.7]


In [105]:
import numpy

# Get N, M and cast to integer
n, m = map(int, input().split())

# Create a N-length array of integers
arrays = numpy.array([input().split(" ") for _ in range(n)], int)
print(arrays)
# Print stats
print(numpy.mean(arrays, axis=1))
print(numpy.var(arrays, axis=0))
print(round(numpy.std(arrays, axis=None), 11))

[[1 2]
 [3 4]]
[ 1.5  3.5]
[ 1.  1.]
1.11803398875
